// Package v1 contains API Schema definitions for the neuvector.com v1 API group.
// +kubebuilder:object:generate=true
// +groupName=neuvector.com
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// GroupName is the group name used in this package.
const GroupName = "neuvector.com"

// SchemeGroupVersion is group version used to register these objects.
//
//nolint:gochecknoglobals // Required to be global by pkg/generated/*
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}

var (
	// GroupVersion is group version used to register these objects.
	//nolint:gochecknoglobals // Generated by kubebuilder
	GroupVersion = schema.GroupVersion{Group: "neuvector.com", Version: "v1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	//nolint:gochecknoglobals // Generated by kubebuilder
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	//nolint:gochecknoglobals // Generated by kubebuilder
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(GroupVersion,
		&NvSecurityRule{},
		&NvClusterSecurityRule{},
	)
	metav1.AddToGroupVersion(s, GroupVersion)
	return nil
}

// Resource takes an unqualified resource and returns back a Group qualified GroupResource.
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}
