package main

const (
	LegacyCaCert = `-----BEGIN CERTIFICATE-----                                             
MIIDcTCCAlmgAwIBAgIJAN+l38eDYtlGMA0GCSqGSIb3DQEBCwUAME8xCzAJBgNV           
BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRcwFQYDVQQKDA5OZXVWZWN0b3Ig           
SW5jLjESMBAGA1UEAwwJTmV1VmVjdG9yMB4XDTE2MDUxOTAyMjE0NFoXDTI2MDUx        
NzAyMjE0NFowTzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFzAV        
BgNVBAoMDk5ldVZlY3RvciBJbmMuMRIwEAYDVQQDDAlOZXVWZWN0b3IwggEiMA0G        
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDPdUAzceXRoLfJ0VWyhgm6j+oyPBnx        
AyGAVG6jFRuJkraln6yctXu04V4GI6bsjGLClGE4dWleoSqslQAy9JPjHTUC0nWC        
ucNMTrNg6so3UcXgy1wzyuiAnCn/xb5Yct8PfP8cmdSWr+D98pLV4mtjBWHIUfrA        
89skLCrbZgPYmbNWSBJ4Z80lQ9J0eQ5LHkHqBnhaZ3a781p6n0qe6UQ+wNDl7ZaD        
XS2kmfQYY1rFZ4mo7LFPtPtTac3WeMNLDGIJoVwvkrJwRlm8TEB3zvkK1lxCeiHI        
ClnIq1cgpw5mqiC16ofFkxyFPT+ZBBOPdB55OxFO1SIPnlb+jK2tN74bAgMBAAGj        
UDBOMB0GA1UdDgQWBBSulkDMGbtLm/vz34w1ofRKW2A8FjAfBgNVHSMEGDAWgBSu        
lkDMGbtLm/vz34w1ofRKW2A8FjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUA        
A4IBAQCjUpl9eutrMDv3oZ7sk9vgjbnPK7PvEFz3KdyH+SJAfVUYb17L2g0uQu98        
frctKAXbVxw3LAYmEJ//swB9k+QKLKSR5zHfdU4Vn8nFLBc+aQD6ofAK/T1B7/6u        
J9VEh1o5y7ylv+eBiGhEsYROVsIdZYoq/W1D6yNqqRtRiMyF992SaDYqNM0uB+Yq        
ZSdB2nJFM0dnuDzpJT0akR8u5lbz24iFNuWOFWP5T32m/zsWJMv9FDbQni7YTdUl        
6RRnXGUbx1XqVSitF6L6b6hM0dkOecTe8COr08g4gS5aM/iZrD8u2HO/TMs5hEtt        
ztOYM3AlH81tlNyy/JxJ/DKDInvw                                            
-----END CERTIFICATE-----`

	LegacyCert = `-----BEGIN CERTIFICATE-----                                             
MIIDVTCCAj2gAwIBAgIJAOwrtkGjN0VJMA0GCSqGSIb3DQEBCwUAME8xCzAJBgNV           
BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRcwFQYDVQQKDA5OZXVWZWN0b3Ig           
SW5jLjESMBAGA1UEAwwJTmV1VmVjdG9yMB4XDTIyMTExODE4MjkzNFoXDTMyMTEx        
NTE4MjkzNFowdjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExETAP        
BgNVBAcTCFNhbiBKb3NlMRcwFQYDVQQKEw5OZXVWZWN0b3IgSW5jLjESMBAGA1UE        
CxMJTmV1VmVjdG9yMRIwEAYDVQQDEwlOZXVWZWN0b3IwgZ8wDQYJKoZIhvcNAQEB        
BQADgY0AMIGJAoGBAMIEI/tMw/zk3xG3H2MR7XzkR/PHSHVMQlIHuUuZhB+eEfUg        
AS44oaRMSC5FFDWzrJ7zHRMgCjXPzaR3baOoUl+nSpamIiAf2Ee6Gor+pUSH3X4K        
jENXFYvvExFnxA7SiMOwvhqoCk3eICIErCtkfhW7/3IdXhN7nhw9lxVGKiBZAgMB        
AAGjgZAwgY0wCQYDVR0TBAIwADALBgNVHQ8EBAMCBLAwHQYDVR0lBBYwFAYIKwYB        
BQUHAwEGCCsGAQUFBwMCMBQGA1UdEQQNMAuCCU5ldVZlY3RvcjAdBgNVHQ4EFgQU        
iRAI9mCFBuqCQe5RKvxEZzvZ1j0wHwYDVR0jBBgwFoAUrpZAzBm7S5v789+MNaH0        
SltgPBYwDQYJKoZIhvcNAQELBQADggEBAFZixf9mmiuEKIYb8IxuGRP47ADKToEW        
uj0xx67mkoAykF+Smd0qb+2yQej83Btorx6lL0rV+cYjcycgFeYJW9O98cLT8Zp/        
zsxnXkuv2XuCsOYkgo+Ug+FkpvyhX8FugvNLToNV+MaBQJjVcyjCwETWIrhSiKJd        
ddJSflgVsxxT0D5CQ4vTlh5yIbJ3VDnBQ5M8cNKTCwjpVNY2GPPsDVV0IfOAU+/3        
j/lVgg90UR2qd7eR3VNQjvGutRrkmdgyKVVZylVsk7B6bGCNaKCXL5tTQipdEBsU        
hGqsHmKIhmOnC0/PQ2+h/Qcdvkd00Cx734VRZSbmfeOUYe6sL7qOSFA=                
-----END CERTIFICATE-----`
	LegacyKey = `-----BEGIN PRIVATE KEY-----                                             
MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAMIEI/tMw/zk3xG3           
H2MR7XzkR/PHSHVMQlIHuUuZhB+eEfUgAS44oaRMSC5FFDWzrJ7zHRMgCjXPzaR3           
baOoUl+nSpamIiAf2Ee6Gor+pUSH3X4KjENXFYvvExFnxA7SiMOwvhqoCk3eICIE        
rCtkfhW7/3IdXhN7nhw9lxVGKiBZAgMBAAECgYBGGvrpdk6nVggovZPQ14yKAW7i        
bpMHF3wrafERmTI9vn9cpKjoi7wUwx+d4IYx9W+dq9lIrN4jnagAEsuCRHMmzfQ7        
10Ho/B6867jsKZpRWJeOY7R56DCOAng7nDsZTu7+gFkd8c2DeHkFXfPe1dkxkkNs        
TAJhQPjBcXoHcC7vtQJBAOjYMufjS56z6021kFziPIVA/KTxFk9IjDU8xx6I5LNK        
xZYa+3Bx08zuxCX5HuO9ePsHSjL8zTIVIz8j/DC6QF8CQQDVT3Ekhl7SlxoINK37        
FSW1DFEw0hX8hUUjkg3qgMyMGWJP9T6677wsMRkgjbOMLbo9T2OxL5ZbEcBmM8hc        
S3pHAkA1KHamvhubhdPoj9T/f571hRqoxWmkfBmWZePHstUTobRuSoaw6yvBk5kw        
WimVMMKX/NgRv+lQz8aWOa7vqPXdAkBjYQigcK3axSUOr6Ri9x5DNELbUPWHWXu1        
r8Ul/O3PU8A26lZYd3qeyB0hyoLdCyzahZM3qKkPMr0FoJh3T37fAkA+AMRsd61J        
YlwDknI804TNMk0uhqGG3FmS4+auX7lZnx7lbr1qWDBvuWikr7FDmF6k80A5756l        
WGvaU0PDPN+q                                                            
-----END PRIVATE KEY-----`
)
