// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan.proto

package share

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ScanErrorCode int32

const (
	ScanErrorCode_ScanErrNone                ScanErrorCode = 0
	ScanErrorCode_ScanErrNetwork             ScanErrorCode = 1
	ScanErrorCode_ScanErrNotSupport          ScanErrorCode = 2
	ScanErrorCode_ScanErrSizeOverLimit       ScanErrorCode = 3
	ScanErrorCode_ScanErrPackage             ScanErrorCode = 4
	ScanErrorCode_ScanErrDatabase            ScanErrorCode = 5
	ScanErrorCode_ScanErrTimeout             ScanErrorCode = 6
	ScanErrorCode_ScanErrInProgress          ScanErrorCode = 7
	ScanErrorCode_ScanErrRegistryAPI         ScanErrorCode = 8
	ScanErrorCode_ScanErrFileSystem          ScanErrorCode = 9
	ScanErrorCode_ScanErrContainerAPI        ScanErrorCode = 10
	ScanErrorCode_ScanErrXrayAPI             ScanErrorCode = 11
	ScanErrorCode_ScanErrContainerExit       ScanErrorCode = 12
	ScanErrorCode_ScanErrAuthentication      ScanErrorCode = 13
	ScanErrorCode_ScanErrCertificate         ScanErrorCode = 14
	ScanErrorCode_ScanErrCanceled            ScanErrorCode = 15
	ScanErrorCode_ScanErrDriverAPINotSupport ScanErrorCode = 16
	ScanErrorCode_ScanErrImageNotFound       ScanErrorCode = 17
	ScanErrorCode_ScanErrAwsDownloadErr      ScanErrorCode = 18
	ScanErrorCode_ScanErrArgument            ScanErrorCode = 19
)

var ScanErrorCode_name = map[int32]string{
	0:  "ScanErrNone",
	1:  "ScanErrNetwork",
	2:  "ScanErrNotSupport",
	3:  "ScanErrSizeOverLimit",
	4:  "ScanErrPackage",
	5:  "ScanErrDatabase",
	6:  "ScanErrTimeout",
	7:  "ScanErrInProgress",
	8:  "ScanErrRegistryAPI",
	9:  "ScanErrFileSystem",
	10: "ScanErrContainerAPI",
	11: "ScanErrXrayAPI",
	12: "ScanErrContainerExit",
	13: "ScanErrAuthentication",
	14: "ScanErrCertificate",
	15: "ScanErrCanceled",
	16: "ScanErrDriverAPINotSupport",
	17: "ScanErrImageNotFound",
	18: "ScanErrAwsDownloadErr",
	19: "ScanErrArgument",
}
var ScanErrorCode_value = map[string]int32{
	"ScanErrNone":                0,
	"ScanErrNetwork":             1,
	"ScanErrNotSupport":          2,
	"ScanErrSizeOverLimit":       3,
	"ScanErrPackage":             4,
	"ScanErrDatabase":            5,
	"ScanErrTimeout":             6,
	"ScanErrInProgress":          7,
	"ScanErrRegistryAPI":         8,
	"ScanErrFileSystem":          9,
	"ScanErrContainerAPI":        10,
	"ScanErrXrayAPI":             11,
	"ScanErrContainerExit":       12,
	"ScanErrAuthentication":      13,
	"ScanErrCertificate":         14,
	"ScanErrCanceled":            15,
	"ScanErrDriverAPINotSupport": 16,
	"ScanErrImageNotFound":       17,
	"ScanErrAwsDownloadErr":      18,
	"ScanErrArgument":            19,
}

func (x ScanErrorCode) String() string {
	return proto.EnumName(ScanErrorCode_name, int32(x))
}
func (ScanErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type ScanObjectType int32

const (
	ScanObjectType_CONTAINER  ScanObjectType = 0
	ScanObjectType_HOST       ScanObjectType = 1
	ScanObjectType_IMAGE      ScanObjectType = 2
	ScanObjectType_PLATFORM   ScanObjectType = 3
	ScanObjectType_SERVERLESS ScanObjectType = 4
)

var ScanObjectType_name = map[int32]string{
	0: "CONTAINER",
	1: "HOST",
	2: "IMAGE",
	3: "PLATFORM",
	4: "SERVERLESS",
}
var ScanObjectType_value = map[string]int32{
	"CONTAINER":  0,
	"HOST":       1,
	"IMAGE":      2,
	"PLATFORM":   3,
	"SERVERLESS": 4,
}

func (x ScanObjectType) String() string {
	return proto.EnumName(ScanObjectType_name, int32(x))
}
func (ScanObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type ScanProvider int32

const (
	ScanProvider_Neuvector ScanProvider = 0
	ScanProvider_JFrogXray ScanProvider = 1
)

var ScanProvider_name = map[int32]string{
	0: "Neuvector",
	1: "JFrogXray",
}
var ScanProvider_value = map[string]int32{
	"Neuvector": 0,
	"JFrogXray": 1,
}

func (x ScanProvider) String() string {
	return proto.EnumName(ScanProvider_name, int32(x))
}
func (ScanProvider) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type ScanVulStatus int32

const (
	ScanVulStatus_Unpatched  ScanVulStatus = 0
	ScanVulStatus_FixExists  ScanVulStatus = 1
	ScanVulStatus_WillNotFix ScanVulStatus = 2
	ScanVulStatus_Unaffected ScanVulStatus = 3
)

var ScanVulStatus_name = map[int32]string{
	0: "Unpatched",
	1: "FixExists",
	2: "WillNotFix",
	3: "Unaffected",
}
var ScanVulStatus_value = map[string]int32{
	"Unpatched":  0,
	"FixExists":  1,
	"WillNotFix": 2,
	"Unaffected": 3,
}

func (x ScanVulStatus) String() string {
	return proto.EnumName(ScanVulStatus_name, int32(x))
}
func (ScanVulStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type ScanVulnerability struct {
	Name             string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Score            float32  `protobuf:"fixed32,2,opt,name=Score" json:"Score,omitempty"`
	Severity         string   `protobuf:"bytes,3,opt,name=Severity" json:"Severity,omitempty"`
	Description      string   `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	PackageName      string   `protobuf:"bytes,5,opt,name=PackageName" json:"PackageName,omitempty"`
	PackageVersion   string   `protobuf:"bytes,6,opt,name=PackageVersion" json:"PackageVersion,omitempty"`
	FixedVersion     string   `protobuf:"bytes,7,opt,name=FixedVersion" json:"FixedVersion,omitempty"`
	Link             string   `protobuf:"bytes,8,opt,name=Link" json:"Link,omitempty"`
	Vectors          string   `protobuf:"bytes,9,opt,name=Vectors" json:"Vectors,omitempty"`
	ScoreV3          float32  `protobuf:"fixed32,10,opt,name=ScoreV3" json:"ScoreV3,omitempty"`
	VectorsV3        string   `protobuf:"bytes,11,opt,name=VectorsV3" json:"VectorsV3,omitempty"`
	PublishedDate    string   `protobuf:"bytes,12,opt,name=PublishedDate" json:"PublishedDate,omitempty"`
	LastModifiedDate string   `protobuf:"bytes,13,opt,name=LastModifiedDate" json:"LastModifiedDate,omitempty"`
	CPEs             []string `protobuf:"bytes,14,rep,name=CPEs" json:"CPEs,omitempty"`
	CVEs             []string `protobuf:"bytes,15,rep,name=CVEs" json:"CVEs,omitempty"`
	FeedRating       string   `protobuf:"bytes,16,opt,name=FeedRating" json:"FeedRating,omitempty"`
	InBase           bool     `protobuf:"varint,17,opt,name=InBase" json:"InBase,omitempty"`
	DBKey            string   `protobuf:"bytes,18,opt,name=DBKey" json:"DBKey,omitempty"`
	FileName         string   `protobuf:"bytes,19,opt,name=FileName" json:"FileName,omitempty"`
}

func (m *ScanVulnerability) Reset()                    { *m = ScanVulnerability{} }
func (m *ScanVulnerability) String() string            { return proto.CompactTextString(m) }
func (*ScanVulnerability) ProtoMessage()               {}
func (*ScanVulnerability) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ScanVulnerability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanVulnerability) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ScanVulnerability) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *ScanVulnerability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScanVulnerability) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ScanVulnerability) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

func (m *ScanVulnerability) GetFixedVersion() string {
	if m != nil {
		return m.FixedVersion
	}
	return ""
}

func (m *ScanVulnerability) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *ScanVulnerability) GetVectors() string {
	if m != nil {
		return m.Vectors
	}
	return ""
}

func (m *ScanVulnerability) GetScoreV3() float32 {
	if m != nil {
		return m.ScoreV3
	}
	return 0
}

func (m *ScanVulnerability) GetVectorsV3() string {
	if m != nil {
		return m.VectorsV3
	}
	return ""
}

func (m *ScanVulnerability) GetPublishedDate() string {
	if m != nil {
		return m.PublishedDate
	}
	return ""
}

func (m *ScanVulnerability) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *ScanVulnerability) GetCPEs() []string {
	if m != nil {
		return m.CPEs
	}
	return nil
}

func (m *ScanVulnerability) GetCVEs() []string {
	if m != nil {
		return m.CVEs
	}
	return nil
}

func (m *ScanVulnerability) GetFeedRating() string {
	if m != nil {
		return m.FeedRating
	}
	return ""
}

func (m *ScanVulnerability) GetInBase() bool {
	if m != nil {
		return m.InBase
	}
	return false
}

func (m *ScanVulnerability) GetDBKey() string {
	if m != nil {
		return m.DBKey
	}
	return ""
}

func (m *ScanVulnerability) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type ScanLayerResult struct {
	Digest  string               `protobuf:"bytes,1,opt,name=Digest" json:"Digest,omitempty"`
	Vuls    []*ScanVulnerability `protobuf:"bytes,2,rep,name=Vuls" json:"Vuls,omitempty"`
	Cmds    string               `protobuf:"bytes,3,opt,name=Cmds" json:"Cmds,omitempty"`
	Size    int64                `protobuf:"varint,4,opt,name=Size" json:"Size,omitempty"`
	Secrets *ScanSecretResult    `protobuf:"bytes,5,opt,name=Secrets" json:"Secrets,omitempty"`
}

func (m *ScanLayerResult) Reset()                    { *m = ScanLayerResult{} }
func (m *ScanLayerResult) String() string            { return proto.CompactTextString(m) }
func (*ScanLayerResult) ProtoMessage()               {}
func (*ScanLayerResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ScanLayerResult) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ScanLayerResult) GetVuls() []*ScanVulnerability {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanLayerResult) GetCmds() string {
	if m != nil {
		return m.Cmds
	}
	return ""
}

func (m *ScanLayerResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ScanLayerResult) GetSecrets() *ScanSecretResult {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ScanModule struct {
	Name    string           `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version string           `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
	Source  string           `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Vuls    []*ScanModuleVul `protobuf:"bytes,4,rep,name=Vuls" json:"Vuls,omitempty"`
	CPEs    []string         `protobuf:"bytes,5,rep,name=CPEs" json:"CPEs,omitempty"`
}

func (m *ScanModule) Reset()                    { *m = ScanModule{} }
func (m *ScanModule) String() string            { return proto.CompactTextString(m) }
func (*ScanModule) ProtoMessage()               {}
func (*ScanModule) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ScanModule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanModule) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanModule) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ScanModule) GetVuls() []*ScanModuleVul {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanModule) GetCPEs() []string {
	if m != nil {
		return m.CPEs
	}
	return nil
}

type ScanModuleVul struct {
	Name   string        `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Status ScanVulStatus `protobuf:"varint,2,opt,name=Status,enum=share.ScanVulStatus" json:"Status,omitempty"`
}

func (m *ScanModuleVul) Reset()                    { *m = ScanModuleVul{} }
func (m *ScanModuleVul) String() string            { return proto.CompactTextString(m) }
func (*ScanModuleVul) ProtoMessage()               {}
func (*ScanModuleVul) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ScanModuleVul) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScanModuleVul) GetStatus() ScanVulStatus {
	if m != nil {
		return m.Status
	}
	return ScanVulStatus_Unpatched
}

type ScanSecretLog struct {
	Type       string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
	File       string `protobuf:"bytes,3,opt,name=File" json:"File,omitempty"`
	RuleDesc   string `protobuf:"bytes,4,opt,name=RuleDesc" json:"RuleDesc,omitempty"`
	Suggestion string `protobuf:"bytes,5,opt,name=Suggestion" json:"Suggestion,omitempty"`
}

func (m *ScanSecretLog) Reset()                    { *m = ScanSecretLog{} }
func (m *ScanSecretLog) String() string            { return proto.CompactTextString(m) }
func (*ScanSecretLog) ProtoMessage()               {}
func (*ScanSecretLog) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *ScanSecretLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ScanSecretLog) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ScanSecretLog) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ScanSecretLog) GetRuleDesc() string {
	if m != nil {
		return m.RuleDesc
	}
	return ""
}

func (m *ScanSecretLog) GetSuggestion() string {
	if m != nil {
		return m.Suggestion
	}
	return ""
}

type ScanSecretResult struct {
	Error ScanErrorCode    `protobuf:"varint,1,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Logs  []*ScanSecretLog `protobuf:"bytes,2,rep,name=Logs" json:"Logs,omitempty"`
}

func (m *ScanSecretResult) Reset()                    { *m = ScanSecretResult{} }
func (m *ScanSecretResult) String() string            { return proto.CompactTextString(m) }
func (*ScanSecretResult) ProtoMessage()               {}
func (*ScanSecretResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *ScanSecretResult) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanSecretResult) GetLogs() []*ScanSecretLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ScanSetIdPermLog struct {
	Type     string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	File     string `protobuf:"bytes,2,opt,name=File" json:"File,omitempty"`
	Evidence string `protobuf:"bytes,3,opt,name=Evidence" json:"Evidence,omitempty"`
}

func (m *ScanSetIdPermLog) Reset()                    { *m = ScanSetIdPermLog{} }
func (m *ScanSetIdPermLog) String() string            { return proto.CompactTextString(m) }
func (*ScanSetIdPermLog) ProtoMessage()               {}
func (*ScanSetIdPermLog) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ScanSetIdPermLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ScanSetIdPermLog) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ScanSetIdPermLog) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

type ScanResult struct {
	Version                        string               `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Error                          ScanErrorCode        `protobuf:"varint,2,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Namespace                      string               `protobuf:"bytes,3,opt,name=Namespace" json:"Namespace,omitempty"`
	Vuls                           []*ScanVulnerability `protobuf:"bytes,4,rep,name=Vuls" json:"Vuls,omitempty"`
	ContainerID                    string               `protobuf:"bytes,5,opt,name=ContainerID" json:"ContainerID,omitempty"`
	HostID                         string               `protobuf:"bytes,6,opt,name=HostID" json:"HostID,omitempty"`
	Registry                       string               `protobuf:"bytes,7,opt,name=Registry" json:"Registry,omitempty"`
	Repository                     string               `protobuf:"bytes,8,opt,name=Repository" json:"Repository,omitempty"`
	Tag                            string               `protobuf:"bytes,9,opt,name=Tag" json:"Tag,omitempty"`
	Digest                         string               `protobuf:"bytes,10,opt,name=Digest" json:"Digest,omitempty"`
	ImageID                        string               `protobuf:"bytes,11,opt,name=ImageID" json:"ImageID,omitempty"`
	Layers                         []*ScanLayerResult   `protobuf:"bytes,12,rep,name=Layers" json:"Layers,omitempty"`
	Envs                           []string             `protobuf:"bytes,13,rep,name=Envs" json:"Envs,omitempty"`
	Labels                         map[string]string    `protobuf:"bytes,14,rep,name=Labels" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platform                       string               `protobuf:"bytes,15,opt,name=Platform" json:"Platform,omitempty"`
	PlatformVersion                string               `protobuf:"bytes,16,opt,name=PlatformVersion" json:"PlatformVersion,omitempty"`
	Author                         string               `protobuf:"bytes,17,opt,name=Author" json:"Author,omitempty"`
	CVEDBCreateTime                string               `protobuf:"bytes,18,opt,name=CVEDBCreateTime" json:"CVEDBCreateTime,omitempty"`
	Modules                        []*ScanModule        `protobuf:"bytes,19,rep,name=Modules" json:"Modules,omitempty"`
	Secrets                        *ScanSecretResult    `protobuf:"bytes,20,opt,name=Secrets" json:"Secrets,omitempty"`
	Cmds                           []string             `protobuf:"bytes,21,rep,name=Cmds" json:"Cmds,omitempty"`
	SetIdPerms                     []*ScanSetIdPermLog  `protobuf:"bytes,22,rep,name=SetIdPerms" json:"SetIdPerms,omitempty"`
	Provider                       ScanProvider         `protobuf:"varint,23,opt,name=Provider,enum=share.ScanProvider" json:"Provider,omitempty"`
	Size                           int64                `protobuf:"varint,24,opt,name=Size" json:"Size,omitempty"`
	Verifiers                      []string             `protobuf:"bytes,25,rep,name=Verifiers" json:"Verifiers,omitempty"`
	SignatureVerificationError     ScanErrorCode        `protobuf:"varint,26,opt,name=SignatureVerificationError,enum=share.ScanErrorCode" json:"SignatureVerificationError,omitempty"`
	SignatureVerificationTimestamp string               `protobuf:"bytes,27,opt,name=SignatureVerificationTimestamp" json:"SignatureVerificationTimestamp,omitempty"`
}

func (m *ScanResult) Reset()                    { *m = ScanResult{} }
func (m *ScanResult) String() string            { return proto.CompactTextString(m) }
func (*ScanResult) ProtoMessage()               {}
func (*ScanResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *ScanResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanResult) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanResult) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ScanResult) GetVuls() []*ScanVulnerability {
	if m != nil {
		return m.Vuls
	}
	return nil
}

func (m *ScanResult) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *ScanResult) GetHostID() string {
	if m != nil {
		return m.HostID
	}
	return ""
}

func (m *ScanResult) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *ScanResult) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *ScanResult) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ScanResult) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ScanResult) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

func (m *ScanResult) GetLayers() []*ScanLayerResult {
	if m != nil {
		return m.Layers
	}
	return nil
}

func (m *ScanResult) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *ScanResult) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ScanResult) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ScanResult) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *ScanResult) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ScanResult) GetCVEDBCreateTime() string {
	if m != nil {
		return m.CVEDBCreateTime
	}
	return ""
}

func (m *ScanResult) GetModules() []*ScanModule {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *ScanResult) GetSecrets() *ScanSecretResult {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *ScanResult) GetCmds() []string {
	if m != nil {
		return m.Cmds
	}
	return nil
}

func (m *ScanResult) GetSetIdPerms() []*ScanSetIdPermLog {
	if m != nil {
		return m.SetIdPerms
	}
	return nil
}

func (m *ScanResult) GetProvider() ScanProvider {
	if m != nil {
		return m.Provider
	}
	return ScanProvider_Neuvector
}

func (m *ScanResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ScanResult) GetVerifiers() []string {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

func (m *ScanResult) GetSignatureVerificationError() ScanErrorCode {
	if m != nil {
		return m.SignatureVerificationError
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanResult) GetSignatureVerificationTimestamp() string {
	if m != nil {
		return m.SignatureVerificationTimestamp
	}
	return ""
}

type ScanRunningRequest struct {
	Type             ScanObjectType `protobuf:"varint,1,opt,name=Type,enum=share.ScanObjectType" json:"Type,omitempty"`
	ID               string         `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
	AgentID          string         `protobuf:"bytes,3,opt,name=AgentID" json:"AgentID,omitempty"`
	AgentRPCEndPoint string         `protobuf:"bytes,4,opt,name=AgentRPCEndPoint" json:"AgentRPCEndPoint,omitempty"`
}

func (m *ScanRunningRequest) Reset()                    { *m = ScanRunningRequest{} }
func (m *ScanRunningRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanRunningRequest) ProtoMessage()               {}
func (*ScanRunningRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *ScanRunningRequest) GetType() ScanObjectType {
	if m != nil {
		return m.Type
	}
	return ScanObjectType_CONTAINER
}

func (m *ScanRunningRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ScanRunningRequest) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *ScanRunningRequest) GetAgentRPCEndPoint() string {
	if m != nil {
		return m.AgentRPCEndPoint
	}
	return ""
}

type ScanData struct {
	Error  ScanErrorCode `protobuf:"varint,1,opt,name=Error,enum=share.ScanErrorCode" json:"Error,omitempty"`
	Buffer []byte        `protobuf:"bytes,2,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
}

func (m *ScanData) Reset()                    { *m = ScanData{} }
func (m *ScanData) String() string            { return proto.CompactTextString(m) }
func (*ScanData) ProtoMessage()               {}
func (*ScanData) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *ScanData) GetError() ScanErrorCode {
	if m != nil {
		return m.Error
	}
	return ScanErrorCode_ScanErrNone
}

func (m *ScanData) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type ScanAppPackage struct {
	AppName    string `protobuf:"bytes,1,opt,name=AppName" json:"AppName,omitempty"`
	ModuleName string `protobuf:"bytes,2,opt,name=ModuleName" json:"ModuleName,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=Version" json:"Version,omitempty"`
	FileName   string `protobuf:"bytes,4,opt,name=FileName" json:"FileName,omitempty"`
}

func (m *ScanAppPackage) Reset()                    { *m = ScanAppPackage{} }
func (m *ScanAppPackage) String() string            { return proto.CompactTextString(m) }
func (*ScanAppPackage) ProtoMessage()               {}
func (*ScanAppPackage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *ScanAppPackage) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ScanAppPackage) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *ScanAppPackage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ScanAppPackage) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type ScanAppRequest struct {
	Packages []*ScanAppPackage `protobuf:"bytes,1,rep,name=Packages" json:"Packages,omitempty"`
}

func (m *ScanAppRequest) Reset()                    { *m = ScanAppRequest{} }
func (m *ScanAppRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanAppRequest) ProtoMessage()               {}
func (*ScanAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *ScanAppRequest) GetPackages() []*ScanAppPackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

type ScanAwsLambdaRequest struct {
	ResType     string `protobuf:"bytes,1,opt,name=ResType" json:"ResType,omitempty"`
	FuncName    string `protobuf:"bytes,2,opt,name=FuncName" json:"FuncName,omitempty"`
	Region      string `protobuf:"bytes,3,opt,name=Region" json:"Region,omitempty"`
	FuncLink    string `protobuf:"bytes,4,opt,name=FuncLink" json:"FuncLink,omitempty"`
	ScanSecrets bool   `protobuf:"varint,5,opt,name=ScanSecrets" json:"ScanSecrets,omitempty"`
}

func (m *ScanAwsLambdaRequest) Reset()                    { *m = ScanAwsLambdaRequest{} }
func (m *ScanAwsLambdaRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanAwsLambdaRequest) ProtoMessage()               {}
func (*ScanAwsLambdaRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *ScanAwsLambdaRequest) GetResType() string {
	if m != nil {
		return m.ResType
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetFuncLink() string {
	if m != nil {
		return m.FuncLink
	}
	return ""
}

func (m *ScanAwsLambdaRequest) GetScanSecrets() bool {
	if m != nil {
		return m.ScanSecrets
	}
	return false
}

func init() {
	proto.RegisterType((*ScanVulnerability)(nil), "share.ScanVulnerability")
	proto.RegisterType((*ScanLayerResult)(nil), "share.ScanLayerResult")
	proto.RegisterType((*ScanModule)(nil), "share.ScanModule")
	proto.RegisterType((*ScanModuleVul)(nil), "share.ScanModuleVul")
	proto.RegisterType((*ScanSecretLog)(nil), "share.ScanSecretLog")
	proto.RegisterType((*ScanSecretResult)(nil), "share.ScanSecretResult")
	proto.RegisterType((*ScanSetIdPermLog)(nil), "share.ScanSetIdPermLog")
	proto.RegisterType((*ScanResult)(nil), "share.ScanResult")
	proto.RegisterType((*ScanRunningRequest)(nil), "share.ScanRunningRequest")
	proto.RegisterType((*ScanData)(nil), "share.ScanData")
	proto.RegisterType((*ScanAppPackage)(nil), "share.ScanAppPackage")
	proto.RegisterType((*ScanAppRequest)(nil), "share.ScanAppRequest")
	proto.RegisterType((*ScanAwsLambdaRequest)(nil), "share.ScanAwsLambdaRequest")
	proto.RegisterEnum("share.ScanErrorCode", ScanErrorCode_name, ScanErrorCode_value)
	proto.RegisterEnum("share.ScanObjectType", ScanObjectType_name, ScanObjectType_value)
	proto.RegisterEnum("share.ScanProvider", ScanProvider_name, ScanProvider_value)
	proto.RegisterEnum("share.ScanVulStatus", ScanVulStatus_name, ScanVulStatus_value)
}

func init() { proto.RegisterFile("scan.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x72, 0xdb, 0x36,
	0x16, 0x0e, 0x25, 0x59, 0x96, 0x20, 0x5b, 0x86, 0xe1, 0x9f, 0x30, 0xde, 0x6c, 0x46, 0xa3, 0xd9,
	0xd9, 0xf1, 0x7a, 0x33, 0xde, 0x89, 0x33, 0x3b, 0xfb, 0x73, 0x27, 0x4b, 0xd4, 0x46, 0xbb, 0xb2,
	0xad, 0xa5, 0x1c, 0xb5, 0xb7, 0xb0, 0x08, 0xd3, 0xac, 0x29, 0x52, 0x05, 0x40, 0xdb, 0xea, 0x55,
	0xef, 0x7a, 0xdb, 0x9b, 0xbe, 0x40, 0x1f, 0xa1, 0x7d, 0x85, 0xbe, 0x48, 0xdf, 0xa4, 0x73, 0x00,
	0x90, 0x82, 0xec, 0x4c, 0x92, 0xde, 0xe1, 0x1c, 0x7c, 0x04, 0xce, 0x87, 0x73, 0xce, 0x07, 0x10,
	0x21, 0x31, 0xa5, 0xc9, 0xf1, 0x9c, 0xa7, 0x32, 0x25, 0x6b, 0xe2, 0x86, 0x72, 0xd6, 0xfe, 0xb9,
	0x82, 0xb6, 0xc7, 0x53, 0x9a, 0x4c, 0xb2, 0x38, 0x61, 0x9c, 0x5e, 0x45, 0x71, 0x24, 0x17, 0x84,
	0xa0, 0xca, 0x39, 0x9d, 0x31, 0xd7, 0x69, 0x39, 0x87, 0x75, 0x5f, 0x8d, 0xc9, 0x2e, 0x5a, 0x1b,
	0x4f, 0x53, 0xce, 0xdc, 0x52, 0xcb, 0x39, 0x2c, 0xf9, 0xda, 0x20, 0x07, 0xa8, 0x36, 0x66, 0x77,
	0x8c, 0x47, 0x72, 0xe1, 0x96, 0x15, 0xba, 0xb0, 0x49, 0x0b, 0x35, 0x7a, 0x4c, 0x4c, 0x79, 0x34,
	0x97, 0x51, 0x9a, 0xb8, 0x15, 0x35, 0x6d, 0xbb, 0x00, 0x31, 0xa2, 0xd3, 0x5b, 0x1a, 0x32, 0xb5,
	0xdd, 0x9a, 0x46, 0x58, 0x2e, 0xf2, 0x67, 0xd4, 0x34, 0xe6, 0x84, 0x71, 0x01, 0xcb, 0x54, 0x15,
	0xe8, 0x91, 0x97, 0xb4, 0xd1, 0x46, 0x3f, 0x7a, 0x60, 0x41, 0x8e, 0x5a, 0x57, 0xa8, 0x15, 0x1f,
	0xb0, 0x1a, 0x46, 0xc9, 0xad, 0x5b, 0xd3, 0xac, 0x60, 0x4c, 0x5c, 0xb4, 0x3e, 0x61, 0x53, 0x99,
	0x72, 0xe1, 0xd6, 0x95, 0x3b, 0x37, 0x61, 0x46, 0x51, 0x9c, 0xbc, 0x75, 0x91, 0x62, 0x9c, 0x9b,
	0xe4, 0x25, 0xaa, 0x1b, 0xd0, 0xe4, 0xad, 0xdb, 0x50, 0x5f, 0x2d, 0x1d, 0xe4, 0x4f, 0x68, 0x73,
	0x94, 0x5d, 0xc5, 0x91, 0xb8, 0x61, 0x41, 0x8f, 0x4a, 0xe6, 0x6e, 0x28, 0xc4, 0xaa, 0x93, 0x1c,
	0x21, 0x3c, 0xa4, 0x42, 0x9e, 0xa5, 0x41, 0x74, 0x1d, 0x19, 0xe0, 0xa6, 0x02, 0x3e, 0xf1, 0x43,
	0xdc, 0xdd, 0x91, 0x27, 0xdc, 0x66, 0xab, 0x0c, 0x71, 0xc3, 0x58, 0xf9, 0x26, 0x9e, 0x70, 0xb7,
	0x8c, 0x6f, 0xe2, 0x09, 0xf2, 0x0a, 0xa1, 0x3e, 0x63, 0x81, 0x4f, 0x65, 0x94, 0x84, 0x2e, 0x56,
	0xab, 0x59, 0x1e, 0xb2, 0x8f, 0xaa, 0x83, 0xe4, 0x94, 0x0a, 0xe6, 0x6e, 0xb7, 0x9c, 0xc3, 0x9a,
	0x6f, 0x2c, 0xc8, 0x6c, 0xef, 0xf4, 0x7f, 0x6c, 0xe1, 0x12, 0xf5, 0x89, 0x36, 0x20, 0xb3, 0xfd,
	0x28, 0xd6, 0x89, 0xd9, 0xd1, 0x99, 0xcd, 0xed, 0xf6, 0x4f, 0x0e, 0xda, 0x82, 0xaa, 0x19, 0xd2,
	0x05, 0xe3, 0x3e, 0x13, 0x59, 0x2c, 0x61, 0xf5, 0x5e, 0x14, 0x32, 0x21, 0x4d, 0xd5, 0x18, 0x8b,
	0xbc, 0x46, 0x95, 0x49, 0x16, 0x0b, 0xb7, 0xd4, 0x2a, 0x1f, 0x36, 0x4e, 0xdc, 0x63, 0x55, 0x77,
	0xc7, 0x4f, 0x6a, 0xce, 0x57, 0x28, 0xc5, 0x6b, 0x16, 0x08, 0x53, 0x4b, 0x6a, 0x0c, 0xbe, 0x71,
	0xf4, 0x0d, 0x53, 0x05, 0x54, 0xf6, 0xd5, 0x98, 0xbc, 0x41, 0xeb, 0x63, 0x36, 0xe5, 0x4c, 0x0a,
	0x55, 0x35, 0x8d, 0x93, 0xe7, 0xd6, 0xc2, 0x7a, 0x46, 0xc7, 0xe5, 0xe7, 0xb8, 0xf6, 0xf7, 0x0e,
	0x42, 0x30, 0x7b, 0x96, 0x06, 0x59, 0xcc, 0x3e, 0x58, 0xe3, 0xaa, 0x1a, 0x74, 0x01, 0x95, 0xf2,
	0x6a, 0xd0, 0xb5, 0xb3, 0x8f, 0xaa, 0xe3, 0x34, 0xe3, 0x53, 0x66, 0x22, 0x33, 0x16, 0x39, 0x34,
	0xec, 0x2a, 0x8a, 0xdd, 0xae, 0x15, 0x84, 0xde, 0x66, 0x92, 0xc5, 0x16, 0x33, 0xc8, 0xe2, 0xda,
	0x32, 0x8b, 0xed, 0xff, 0xa3, 0xcd, 0x15, 0xe8, 0x07, 0x83, 0x7a, 0x8d, 0xaa, 0x63, 0x49, 0x65,
	0x26, 0x54, 0x4c, 0xcd, 0x95, 0x4d, 0x26, 0x59, 0xac, 0xe7, 0x7c, 0x83, 0x69, 0x7f, 0xe7, 0xe8,
	0x35, 0x35, 0xeb, 0x61, 0x1a, 0xc2, 0x9a, 0x97, 0x8b, 0x79, 0xb1, 0x26, 0x8c, 0x95, 0x8f, 0x3d,
	0x48, 0xc3, 0x52, 0x8d, 0xc1, 0x07, 0x09, 0xce, 0x8f, 0x1e, 0xc6, 0x50, 0x04, 0x7e, 0x16, 0x33,
	0xe8, 0x59, 0xd3, 0xbf, 0x85, 0x0d, 0xe5, 0x36, 0xce, 0x42, 0xc8, 0x31, 0x9c, 0x97, 0xee, 0x5d,
	0xcb, 0xd3, 0xbe, 0x41, 0xf8, 0x71, 0x32, 0xc8, 0x11, 0x5a, 0xf3, 0x38, 0x4f, 0xb9, 0x0a, 0x66,
	0x95, 0x8a, 0xf2, 0x77, 0xd3, 0x80, 0xf9, 0x1a, 0x02, 0x47, 0x3b, 0x4c, 0xc3, 0xbc, 0x70, 0x76,
	0x9f, 0xe4, 0x77, 0x98, 0x86, 0xbe, 0x42, 0xb4, 0x27, 0xf9, 0x4e, 0x72, 0x10, 0x8c, 0x18, 0x9f,
	0x7d, 0x84, 0xb5, 0x62, 0x58, 0x5a, 0x65, 0xe8, 0xdd, 0x45, 0x01, 0x4b, 0x8a, 0xd4, 0x16, 0x76,
	0xfb, 0x97, 0x9a, 0xae, 0x18, 0x13, 0xbc, 0x55, 0x1d, 0xce, 0x6a, 0x75, 0x14, 0xb4, 0x4a, 0x9f,
	0xa6, 0xf5, 0x12, 0xd5, 0x21, 0xad, 0x62, 0x4e, 0x8b, 0x1d, 0x97, 0x8e, 0xa2, 0x5b, 0x2a, 0x9f,
	0xd5, 0x2d, 0x2d, 0xd4, 0xe8, 0xa6, 0x89, 0xa4, 0x51, 0xc2, 0xf8, 0xa0, 0x97, 0xeb, 0xa7, 0xe5,
	0x82, 0xba, 0x7d, 0x97, 0x0a, 0x39, 0xe8, 0x19, 0xdd, 0x34, 0x96, 0x4a, 0x2c, 0x0b, 0x23, 0x21,
	0xf9, 0xc2, 0x68, 0x65, 0x61, 0x43, 0x62, 0x7d, 0x36, 0x4f, 0x45, 0x24, 0x53, 0xbe, 0x30, 0x6a,
	0x69, 0x79, 0x08, 0x46, 0xe5, 0x4b, 0x1a, 0x1a, 0xbd, 0x84, 0xa1, 0xd5, 0xfb, 0x68, 0xa5, 0xf7,
	0x5d, 0xb4, 0x3e, 0x98, 0xd1, 0x90, 0x0d, 0x7a, 0x46, 0x27, 0x73, 0x93, 0x1c, 0xa3, 0xaa, 0x12,
	0x0f, 0xe1, 0x6e, 0x28, 0xa6, 0xfb, 0x16, 0x53, 0x4b, 0x55, 0x7c, 0x83, 0x82, 0xd4, 0x79, 0xc9,
	0x9d, 0x70, 0x37, 0x75, 0xf7, 0xc0, 0x98, 0xfc, 0x1d, 0xd6, 0xb8, 0x62, 0xb1, 0x56, 0xc6, 0xc6,
	0xc9, 0x1f, 0xad, 0x35, 0xf4, 0xe7, 0xc7, 0x7a, 0xde, 0x4b, 0x24, 0x5f, 0xf8, 0x06, 0x0c, 0xd4,
	0x47, 0x31, 0x95, 0xd7, 0x29, 0x9f, 0xb9, 0x5b, 0x9a, 0x7a, 0x6e, 0x93, 0x43, 0xb4, 0x95, 0x8f,
	0xf3, 0x54, 0x6b, 0x1d, 0x7d, 0xec, 0x06, 0xca, 0x9d, 0x4c, 0xde, 0xa4, 0x5c, 0x89, 0x69, 0xdd,
	0x37, 0x16, 0xac, 0xd0, 0x9d, 0x78, 0xbd, 0xd3, 0x2e, 0x67, 0x54, 0xb2, 0xcb, 0x68, 0xc6, 0x8c,
	0xac, 0x3e, 0x76, 0x93, 0xbf, 0xa2, 0x75, 0xdd, 0xf8, 0xc2, 0xdd, 0x51, 0xf1, 0x6f, 0x3f, 0x51,
	0x0f, 0x3f, 0x47, 0xd8, 0x7a, 0xb7, 0xfb, 0x79, 0x7a, 0x57, 0x48, 0xe9, 0x9e, 0x11, 0x1c, 0x90,
	0xd2, 0x7f, 0x20, 0x54, 0x74, 0x89, 0x70, 0xf7, 0xd5, 0xb6, 0xab, 0x2b, 0x2d, 0x5b, 0xc8, 0xb7,
	0xa0, 0xe4, 0x6f, 0xa8, 0x36, 0xe2, 0x29, 0x34, 0x06, 0x77, 0x9f, 0xab, 0x22, 0xdf, 0xb1, 0x3e,
	0xcb, 0xa7, 0xfc, 0x02, 0x54, 0x88, 0xb6, 0x6b, 0x89, 0xb6, 0xba, 0x38, 0x39, 0x5c, 0x6c, 0x5c,
	0xb8, 0x2f, 0x54, 0x58, 0x4b, 0x07, 0xb9, 0x44, 0x07, 0xe3, 0x28, 0x4c, 0xa8, 0xcc, 0x38, 0xd3,
	0xde, 0x29, 0x05, 0x21, 0xd1, 0x9d, 0x75, 0xf0, 0x91, 0xce, 0xfa, 0xc8, 0x77, 0xa4, 0x8f, 0x5e,
	0x7d, 0x70, 0x16, 0x52, 0x20, 0x24, 0x9d, 0xcd, 0xdd, 0x3f, 0xa8, 0xf4, 0x7c, 0x02, 0x75, 0xf0,
	0x2f, 0xd4, 0xb0, 0x8a, 0x09, 0x7a, 0xe0, 0x96, 0x2d, 0x8c, 0x0e, 0xc0, 0x10, 0x6e, 0xd1, 0x3b,
	0x1a, 0x67, 0xb9, 0xba, 0x68, 0xe3, 0xdf, 0xa5, 0x7f, 0x3a, 0xed, 0x1f, 0x1c, 0x44, 0x54, 0x4d,
	0x66, 0x49, 0x12, 0x25, 0xa1, 0xcf, 0xbe, 0xce, 0xa0, 0x39, 0xfe, 0x62, 0x29, 0x54, 0xf3, 0x64,
	0xcf, 0x62, 0x76, 0x71, 0xf5, 0x15, 0x9b, 0x4a, 0x98, 0x34, 0xc2, 0xd5, 0x44, 0xa5, 0x41, 0xcf,
	0x2c, 0x5c, 0x1a, 0xf4, 0xa0, 0xaf, 0x3a, 0x21, 0x4b, 0xa0, 0xad, 0xb5, 0x82, 0xe4, 0x26, 0xbc,
	0x2b, 0xd4, 0xd0, 0x1f, 0x75, 0xbd, 0x24, 0x18, 0xa5, 0x51, 0x22, 0x8d, 0x70, 0x3f, 0xf1, 0xb7,
	0xcf, 0x51, 0x0d, 0x76, 0xeb, 0x51, 0x49, 0x7f, 0x97, 0x30, 0xef, 0xa3, 0xea, 0x69, 0x76, 0x7d,
	0xcd, 0xb4, 0xdc, 0x6d, 0xf8, 0xc6, 0x6a, 0x7f, 0xeb, 0xa0, 0x26, 0x7c, 0xd0, 0x99, 0xcf, 0xcd,
	0xeb, 0x4c, 0x05, 0x3a, 0x9f, 0x5b, 0x57, 0x5a, 0x6e, 0x82, 0xc8, 0xe8, 0xda, 0x56, 0x93, 0x9a,
	0x9a, 0xe5, 0xb1, 0xc5, 0xb6, 0xbc, 0x2a, 0xb6, 0xf6, 0xc3, 0xa4, 0xf2, 0xe8, 0x61, 0xd2, 0x2d,
	0x22, 0xc8, 0x4f, 0xf9, 0x0d, 0xaa, 0x99, 0x60, 0x84, 0xeb, 0xa8, 0x7a, 0xb7, 0x4f, 0x7a, 0x19,
	0xaa, 0x5f, 0xc0, 0xda, 0x3f, 0x3a, 0x68, 0x57, 0x4d, 0xde, 0x8b, 0x21, 0x9d, 0x5d, 0x05, 0x34,
	0x5f, 0xcb, 0x45, 0xeb, 0x3e, 0x13, 0xd6, 0xb5, 0x92, 0x9b, 0x2a, 0xa6, 0x2c, 0x99, 0x5a, 0x5c,
	0x0a, 0x1b, 0x8e, 0x0b, 0xa4, 0xb5, 0x20, 0x62, 0xac, 0xfc, 0x1b, 0xf5, 0x24, 0xad, 0x2c, 0xbf,
	0x51, 0xcf, 0xd2, 0x16, 0x6a, 0x2c, 0x1b, 0x5b, 0x3f, 0x71, 0x6a, 0xbe, 0xed, 0x3a, 0xfa, 0xb5,
	0xac, 0xef, 0xf9, 0x22, 0x3b, 0x64, 0x4b, 0x7f, 0xe3, 0x71, 0x7e, 0x9e, 0x26, 0x0c, 0x3f, 0x23,
	0x44, 0x1f, 0x06, 0x38, 0x98, 0xbc, 0x4f, 0xf9, 0x2d, 0x76, 0xc8, 0x9e, 0x7e, 0xee, 0x2b, 0x90,
	0x1c, 0x67, 0xf3, 0x79, 0xca, 0x25, 0x2e, 0x11, 0x57, 0x33, 0xf6, 0x38, 0x87, 0x46, 0xbd, 0xb8,
	0x63, 0x7c, 0x18, 0xcd, 0x22, 0x89, 0xcb, 0xd6, 0x22, 0xe6, 0x7c, 0x70, 0x85, 0xec, 0xe8, 0xd7,
	0x9f, 0xc7, 0x39, 0xd4, 0xce, 0x15, 0x15, 0x0c, 0xaf, 0x59, 0x40, 0x68, 0x9a, 0x34, 0x93, 0xb8,
	0x6a, 0xed, 0x36, 0x00, 0x8d, 0x08, 0x39, 0x13, 0x02, 0xaf, 0x93, 0x7d, 0xdd, 0x0f, 0x1e, 0xe7,
	0xf9, 0x9d, 0xd3, 0x19, 0x0d, 0x70, 0xcd, 0x82, 0x43, 0x42, 0xc7, 0x0b, 0x21, 0xd9, 0x0c, 0xd7,
	0xc9, 0x73, 0xb4, 0x63, 0xdc, 0xc5, 0xcd, 0x06, 0x78, 0x64, 0x6d, 0xf9, 0x25, 0xa7, 0x6a, 0x8d,
	0x86, 0xc5, 0xa4, 0x00, 0x7b, 0x0f, 0x91, 0xc4, 0x1b, 0xe4, 0x05, 0xda, 0x33, 0x33, 0x20, 0xd5,
	0x2c, 0x91, 0xa6, 0xc7, 0xf1, 0xa6, 0x15, 0x50, 0x97, 0x71, 0xa9, 0xbb, 0x9f, 0xe1, 0xa6, 0x45,
	0xb4, 0x4b, 0x93, 0x29, 0x8b, 0x59, 0x80, 0xb7, 0xc8, 0x2b, 0x74, 0x90, 0xb3, 0xe7, 0xd1, 0x9d,
	0x8a, 0xc5, 0x3a, 0x4b, 0x6c, 0x45, 0xa0, 0x2e, 0xbb, 0xf3, 0x54, 0xf6, 0xd3, 0x2c, 0x09, 0xf0,
	0xb6, 0x1d, 0xc1, 0xbd, 0xe8, 0xa5, 0xf7, 0x49, 0x9c, 0xd2, 0xc0, 0xe3, 0x1c, 0x13, 0x6b, 0xa7,
	0x0e, 0x0f, 0xb3, 0x19, 0x4b, 0x24, 0xde, 0x39, 0xf2, 0x35, 0xbf, 0xa5, 0x1c, 0x90, 0x4d, 0x54,
	0xef, 0x5e, 0x9c, 0x5f, 0x76, 0x06, 0xe7, 0x9e, 0x8f, 0x9f, 0x91, 0x1a, 0xaa, 0xbc, 0xbb, 0x18,
	0x5f, 0x62, 0x87, 0xd4, 0xd1, 0xda, 0xe0, 0xac, 0xf3, 0x1f, 0x0f, 0x97, 0xc8, 0x06, 0xaa, 0x8d,
	0x86, 0x9d, 0xcb, 0xfe, 0x85, 0x7f, 0x86, 0xcb, 0xa4, 0x89, 0xd0, 0xd8, 0xf3, 0x27, 0x9e, 0x3f,
	0xf4, 0xc6, 0x63, 0x5c, 0x39, 0x7a, 0x8d, 0x36, 0x6c, 0xc5, 0x86, 0x15, 0xcf, 0x59, 0x76, 0xa7,
	0x7e, 0x5f, 0xf0, 0x33, 0x30, 0xff, 0xdb, 0xe7, 0x69, 0x08, 0x07, 0x8a, 0x9d, 0xa3, 0x33, 0x5d,
	0x64, 0xc5, 0x33, 0x13, 0xe6, 0xdf, 0x27, 0x73, 0x2a, 0xa7, 0x37, 0x2c, 0xd0, 0xf0, 0x7e, 0xf4,
	0xe0, 0x3d, 0x44, 0x42, 0x0a, 0xec, 0xc0, 0x66, 0x5f, 0x44, 0x71, 0x0c, 0x94, 0xa3, 0x07, 0x5c,
	0x02, 0xfb, 0x7d, 0x42, 0xaf, 0xaf, 0xd9, 0x54, 0xb2, 0x00, 0x97, 0xaf, 0xaa, 0xea, 0xdf, 0xf3,
	0xed, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xc9, 0x92, 0xf4, 0x89, 0x0e, 0x00, 0x00,
}
