name: govulncheck
on:
  push:
    paths:
      - go.sum
      - go.mod
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install Golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true # Always check for the latest patch release
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y libpcre3-dev
      - name: Run govulncheck
        env:
          GOVULNCHECK_VERSION: d1f380186385b4f64e00313f31743df8e4b89a77 # v1.1.4
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@${{ env.GOVULNCHECK_VERSION }}
          govulncheck -C . -format text ./...
