name: Run unitest on push and pull request

on:
  push:
  pull_request:

permissions: {}

jobs:
  unitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: stable
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libpcre3-dev
    - run: |
        ./unitest.sh
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: 18
    - name: openapi-lint 
      run: |
        npm i -g @redocly/cli@1.25.11
        redocly lint controller/api/apis.yaml --skip-rule operation-operationId --skip-rule operation-4xx-response --skip-rule no-ambiguous-paths --skip-rule security-defined
        redocly lint controller/api/internal_apis.yaml --skip-rule operation-operationId
