name: Run unitest on push and pull request

on:
  push:
  pull_request:

permissions: {}

jobs:
  unitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: stable
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libpcre3-dev
    - run: |
        ./unitest.sh
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 18
    - name: openapi-lint 
      run: |
        npm i -g @redocly/cli@1.25.11
        redocly lint controller/api/apis.yaml --skip-rule operation-operationId --skip-rule operation-4xx-response --skip-rule no-ambiguous-paths --skip-rule security-defined
        redocly lint controller/api/internal_apis.yaml --skip-rule operation-operationId
