name: Updatecli
on:
  # Allow to manually trigger Updatecli
  workflow_dispatch:
  # Trigger Updatecli on main branch changes
  # To rebase existing PR
  push:
    branches: [main]
  # Trigger Updatecli pullrequest to test potential changes
  pull_request:
    branches: [main]
  # Periodically checks update
  schedule:
    # Run every hour
    - cron: "0 * * * *"
jobs:
  updatecli:
    name: Run Updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564 # v3.6.0
      - name: Run Updatecli (dryrun)
        if: github.ref != 'refs/heads/main'
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli compose diff --file updatecli/updatecli-compose.yaml"
      - name: Run Updatecli
        if: github.ref == 'refs/heads/main'
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli compose apply --file updatecli/updatecli-compose.yaml"
